stages:
  - deploy

variables:
  CI_DEBUG_TRACE: "true"

deploy_job:
  stage: deploy
  tags:
    - tg_bot  # Тег, связанный с вашим Runner
  script:
    - echo "Pulling the latest code..."
    - git pull origin gitlab main
    - echo "Restarting the Telegram bot service..."
    - systemctl restart bot.service
  only:
    - main  # Выполнять задачу только при пуше в ветку main
