stages:
  - deploy

deploy_job:
  stage: deploy
  tags:
    - tg_bot  # Тег, связанный с вашим Runner
  script:
    - echo "Pulling the latest code..."
    - sudo git pull origin gitlab main
    - echo "Restarting the Telegram bot service..."
    - sudo systemctl restart telegram-bot
  only:
    - main  # Выполнять задачу только при пуше в ветку main
