stages:
  - deploy

variables:
  CI_DEBUG_TRACE: "true"

deploy_job:
  stage: deploy
  tags:
    - tg_bot  # Тег, связанный с вашим Runner
  script:
    - git remote -v
    - echo "Pulling the latest code..."
    - git pull gitlab main
    - echo "Installing/Updating required libraries..."
    - pip install -r requirements.txt  # Установка/обновление библиотек из requirements.txt
    - echo "Restarting the Telegram bot service..."
    - sudo systemctl restart bot.service  # Используйте sudo, если необходимо
  only:
    - main
